### ISSUE TITLE
GDataRequestException - 

### ISSUE THREAD

**Issue by bozok** [google/google-gdata#724]
Hi there,
i am trying to create mail dump request but got an error when i call the below .net code:

MailboxDumpRequest mailboxDumpRequest = new MailboxDumpRequest();
mailboxDumpRequest.BeginDate = new DateTime(2016, 7, 1, 4, 30, 0);
mailboxDumpRequest.EndDate = new DateTime(2016, 8, 30, 20, 0, 0);
mailboxDumpRequest.BeginDate = DateTime.Parse("2016-07-01 10:22"); //new DateTime(2016, 7, 1, 4, 30, 0);
mailboxDumpRequest.EndDate = DateTime.Parse("2016-07-02 10:22"); //new DateTime(2016, 8, 30, 20, 0, 0);
mailboxDumpRequest.IncludeDeleted = true;
mailboxDumpRequest.SearchQuery = "is:unread";
mailboxDumpRequest.PackageContent = MonitorLevel.FULL_MESSAGE;
MailboxDumpRequest dumpRequest = service.CreateMailboxDumpRequest(userKey, mailboxDumpRequest);

and it gives me the following exception error:

Google.GData.Client.GDataRequestException was unhandled
  HResult=-2146233088
  Message=Execution of request failed: https://apps-apis.google.com/a/feeds/compliance/audit/mail/export/{mydomain.com.tr}/{user}
  Source=Google.GData.Client
  ResponseString=<?xml version="1.0" encoding="UTF-8"?>
<AppsForYourDomainErrors>
  <error errorCode="1801" invalidInput="0" reason="InvalidValue" />
</AppsForYourDomainErrors>

any idea for this error code 1801 issue ?

Thank you for your attention.

**Comment by LindaLawton** [comment]
You should not be using the gdata library to access gmail.   I seriously doubt it still works.    

use this https://www.nuget.org/packages/Google.Apis.Gmail.v1/

**Comment by bozok** [comment]
Thank you for your reply, but i am not sure about https://www.nuget.org/packages/Google.Apis.Gmail.v1/ is the right api to export mail archive of users as mbox. Because i've seen that gdata is still breathing for this purpose: 

https://developers.google.com/admin-sdk/email-audit/#managing_a_mailbox_download

**Comment by LindaLawton** [comment]
this library hasn't been worked on in years.   As far as i know no one is currently supporting it.  You might want to try asking on Stackoverflow.  It could be you may get some help there.   You can always just fork the library and fix any problems you have.
